// Hindi (beta). English text is the key. Anything missing falls back to English.
export const HI: Record<string, string> = {
  // hero and navigation
  "Where air and weather": "जहाँ हवा और मौसम",
  "Couple": "जुड़ते हैं",
  "together.": "साथ-साथ।",
  "A 72-hour forecast for Delhi NCR that lets aerosols and meteorology feed back on each other — track inversions, trace stubble plumes, and see the haze coming.":
    "दिल्ली एनसीआर के लिए 72 घंटे का पूर्वानुमान, जिसमें प्रदूषण और मौसम एक-दूसरे को प्रभावित करते हैं। इन्वर्जन परत देखें, पराली के धुएँ का रास्ता पहचानें और धुंध के आने से पहले जानें।",
  "Open live dashboard": "लाइव डैशबोर्ड खोलें",
  "Try the stubble-season what-if": "पराली-मौसम का 'क्या होगा' आज़माएँ",
  "Skip this page next time?": "अगली बार यह पेज छोड़ दें?",
  "Always open dashboard →": "हमेशा डैशबोर्ड खोलें →",
  "Product": "उत्पाद",
  "Resources": "संसाधन",
  "How it works": "यह कैसे काम करता है",
  "Accuracy": "सटीकता",
  "Method": "विधि",
  "Open dashboard": "डैशबोर्ड खोलें",
  "Dashboard": "डैशबोर्ड",
  "72-hour forecast": "72 घंटे का पूर्वानुमान",
  "AQI, PM2.5, PM10, NO₂ and O₃ across 20 NCR stations.": "एनसीआर के 20 स्थानों पर AQI, PM2.5, PM10, NO₂ और O₃।",
  "Two-way feedback": "दोतरफ़ा फीडबैक",
  "Aerosols dim sunlight, the PBL shrinks, PM2.5 rises.": "प्रदूषण धूप रोकता है, सीमा परत सिकुड़ती है, PM2.5 बढ़ता है।",
  "Inversion tracker": "इन्वर्जन ट्रैकर",
  "Strength, PBL height and ventilation, hour by hour.": "इन्वर्जन की ताकत, सीमा परत की ऊँचाई और हवा का बहाव, घंटे-दर-घंटे।",
  "Stubble plume": "पराली का धुआँ",
  "Fire detections carried to Delhi by the forecast wind.": "आग के स्थान, जिनका धुआँ पूर्वानुमानित हवा से दिल्ली पहुँचता है।",
  "Model accuracy": "मॉडल की सटीकता",
  "Held-out stubble-season skill scores.": "उस पराली-मौसम पर स्कोर जो प्रशिक्षण में शामिल नहीं था।",
  "Replay a real episode": "असली प्रदूषण-दौर को दोहराएँ",
  "Nov 2025 forecasts vs what actually happened.": "नवंबर 2025 के पूर्वानुमान बनाम जो वास्तव में हुआ।",
  "Check our work": "हमारी जाँच देखें",
  "Errors by lead time, station and AQI category.": "समय-सीमा, स्थान और AQI श्रेणी के अनुसार त्रुटियाँ।",
  "Method & limitations": "विधि और सीमाएँ",
  "What is real, what is emulated.": "क्या असली है और क्या अनुकरण।",
  "Open API docs": "API दस्तावेज़ खोलें",
  "The forecast as JSON and CSV for your own tools.": "पूर्वानुमान JSON और CSV में, आपके अपने टूल के लिए।",
  "API docs": "API दस्तावेज़",

  // window and controls
  "Delhi NCR HQ": "दिल्ली एनसीआर केंद्र",
  "Delhi NCR": "दिल्ली एनसीआर",
  "Delhi": "दिल्ली",
  "NCR": "एनसीआर",
  "Live": "लाइव",
  "Stubble-season what-if": "पराली-मौसम: क्या होगा",
  "Scenario · synthetic fires": "परिदृश्य · कृत्रिम आग",
  "Live data": "लाइव डेटा",
  "offline cache": "ऑफ़लाइन कैश",
  "CSV": "CSV",
  "Refresh": "रीफ़्रेश",
  "Could not load forecast": "पूर्वानुमान लोड नहीं हो सका",
  "Is the backend running on :8000?": "क्या बैकएंड :8000 पर चल रहा है?",
  "Updated": "अपडेट किया गया",
  "Stubble belt": "पराली क्षेत्र",
  "Light": "हल्का",
  "AQI": "AQI",
  "Fires": "आग",
  "Plume": "धुआँ",
  "Source": "स्रोत",
  "Now (analysis)": "अभी (विश्लेषण)",
  "forecast": "पूर्वानुमान",
  "Air": "हवा",
  "Weather": "मौसम",
  "Smoke": "धुआँ",
  "Why": "क्यों",

  // AQI categories
  "Good": "अच्छा",
  "Satisfactory": "संतोषजनक",
  "Moderate": "मध्यम",
  "Poor": "खराब",
  "Very Poor": "बहुत खराब",
  "Severe": "गंभीर",
  "Very Poor+": "बहुत खराब या उससे ऊपर",

  // AQI card
  "Delhi (11-station mean)": "दिल्ली (11 स्थानों का औसत)",
  "Coupled AQI": "फीडबैक के साथ AQI",
  "vs uncoupled": "बिना फीडबैक के",
  "from feedback": "फीडबैक से",
  "dominant": "मुख्य प्रदूषक",
  "72-hour AQI outlook (tap a bar)": "72 घंटे का AQI अनुमान (किसी पट्टी पर टैप करें)",

  // inversion
  "Atmospheric inversion": "वायुमंडलीय इन्वर्जन",
  "T(925 hPa) − T(surface). Positive = warm air lid trapping pollutants.": "T(925 hPa) − T(सतह)। धनात्मक = गर्म हवा का ढक्कन जो प्रदूषण को फँसाता है।",
  "None": "कोई नहीं",
  "Weak": "कमज़ोर",
  "Strong": "तेज़",
  "inversion": "इन्वर्जन",
  "PBL height": "सीमा परत (PBL) की ऊँचाई",
  "Ventilation": "हवा का बहाव",
  "very poor": "बहुत कम",
  "poor": "कम",
  "adequate": "पर्याप्त",
  "Trapping factor": "फँसाव गुणक",
  "of moderate/strong inversion in the next 72 h": "अगले 72 घंटों में मध्यम/तेज़ इन्वर्जन",
  "peak": "शिखर",
  "at": "पर",
  "lowest PBL": "सबसे कम PBL",

  // feedback
  "Two-way weather ↔ chemistry feedback": "मौसम ↔ रसायन का दोतरफ़ा फीडबैक",
  "Aerosols dim sunlight → cooler surface, shallower PBL → more trapped PM2.5. Iterated to convergence.": "प्रदूषण धूप घटाता है → सतह ठंडी, PBL उथली → PM2.5 ज़्यादा फँसता है। स्थिर उत्तर आने तक दोहराया जाता है।",
  "Temp": "तापमान",
  "Coupled (with feedback)": "फीडबैक के साथ",
  "Uncoupled (one-way)": "बिना फीडबैक (एकतरफ़ा)",
  "NWP (no aerosol feedback)": "मौसम मॉडल (प्रदूषण-फीडबैक के बिना)",
  "Delhi mean": "दिल्ली औसत",
  "PM2.5 uplift": "PM2.5 में बढ़ोतरी",
  "max": "अधिकतम",
  "Daytime cooling": "दिन में ठंडक",
  "Daytime PBL": "दिन की PBL",
  "vs NWP": "मौसम मॉडल की तुलना में",
  "Coupling loop": "फीडबैक चक्र",
  "iterations": "दोहराव",
  "residual": "बचा अंतर",

  // plume
  "Stubble-burning plume": "पराली जलाने का धुआँ",
  "Synthetic peak-season fires (scenario)": "चरम मौसम की कृत्रिम आग (परिदृश्य)",
  "Real NASA FIRMS VIIRS detections, last 24 h": "NASA FIRMS VIIRS से असली पहचान, पिछले 24 घंटे",
  "No active fire detections over Punjab/Haryana in the last 24 h (off-season). Switch to the stubble-season what-if to see plume dispersion.": "पिछले 24 घंटे में पंजाब/हरियाणा में कोई सक्रिय आग नहीं मिली (ऑफ़-सीज़न)। धुएँ का फैलाव देखने के लिए पराली-मौसम का 'क्या होगा' चुनें।",
  "Fire detections": "आग की पहचान",
  "total FRP": "कुल FRP",
  "Reaches Delhi": "दिल्ली पहुँचता है",
  "Already": "पहले से",
  "mean >5 µg/m³": "औसत >5 µg/m³",
  "Peak contribution": "सबसे ज़्यादा योगदान",
  "Transport": "परिवहन",
  "wind from (Delhi)": "हवा की दिशा (दिल्ली)",
  "Stubble PM2.5 at Delhi": "दिल्ली में पराली का PM2.5",

  // forecast chart
  "PM2.5 forecast": "PM2.5 पूर्वानुमान",
  "Click a station on the map to switch. Live mode is compared against the CAMS global-model baseline.": "बदलने के लिए नक्शे पर किसी स्थान पर क्लिक करें। लाइव मोड की तुलना CAMS वैश्विक मॉडल से होती है।",
  "The shaded range covered": "छायांकित दायरे ने कवर किया",
  "of real values on the held-out season (target 80%): a little too narrow.": "असली मानों को उस मौसम में (लक्ष्य 80%): थोड़ा संकरा।",
  "AirCouple (coupled)": "AirCouple (फीडबैक के साथ)",
  "Uncoupled": "बिना फीडबैक",
  "CAMS baseline (global model)": "CAMS आधार (वैश्विक मॉडल)",
  "Likely range (10th–90th percentile)": "संभावित दायरा (10वाँ–90वाँ प्रतिशतक)",

  // attribution, advisory, scenario
  "Why is PM2.5 high?": "PM2.5 ज़्यादा क्यों है?",
  "Delhi-mean PM2.5 split into its causes, adding up exactly to the coupled forecast.": "दिल्ली के औसत PM2.5 को उसके कारणों में बाँटा गया है, जो मिलकर ठीक पूर्वानुमान के बराबर होते हैं।",
  "Background (regional + local)": "पृष्ठभूमि (क्षेत्रीय + स्थानीय)",
  "Feedback amplification": "फीडबैक से बढ़ोतरी",
  "Background": "पृष्ठभूमि",
  "Stubble": "पराली",
  "Feedback": "फीडबैक",
  "share of 72 h PM2.5": "72 घंटे के PM2.5 का हिस्सा",
  "Health advisory": "स्वास्थ्य सलाह",
  "CPCB guidance for": "CPCB मार्गदर्शन",
  "Best next 24 h": "अगले 24 घंटे में सबसे अच्छा",
  "Worst in 72 h": "72 घंटे में सबसे खराब",
  "Hours > 300": "300 से ऊपर के घंटे",
  "Air quality is satisfactory. Minimal health impact.": "वायु गुणवत्ता संतोषजनक है। स्वास्थ्य पर बहुत कम असर।",
  "Normal outdoor activity is fine.": "बाहर की सामान्य गतिविधि ठीक है।",
  "Minor breathing discomfort possible for very sensitive people.": "बहुत संवेदनशील लोगों को हल्की साँस की तकलीफ़ हो सकती है।",
  "Sensitive groups may limit long outdoor exertion.": "संवेदनशील लोग लंबी बाहरी मेहनत सीमित रखें।",
  "Breathing discomfort for people with lung or heart disease, children and older adults.": "फेफड़े या हृदय रोग वाले लोगों, बच्चों और बुज़ुर्गों को साँस की तकलीफ़।",
  "Sensitive groups should reduce prolonged outdoor exertion.": "संवेदनशील लोग लंबे समय तक बाहर मेहनत कम करें।",
  "Keep reliever medication handy.": "राहत देने वाली दवा पास रखें।",
  "Breathing discomfort for most people on prolonged exposure.": "ज़्यादा देर रहने पर ज़्यादातर लोगों को साँस की तकलीफ़।",
  "Avoid long outdoor exercise.": "बाहर लंबी कसरत से बचें।",
  "Sensitive groups stay indoors where possible.": "संवेदनशील लोग जहाँ तक हो सके घर के अंदर रहें।",
  "Consider an N95 mask outdoors.": "बाहर N95 मास्क पहनने पर विचार करें।",
  "Respiratory illness on prolonged exposure; serious for people with existing disease.": "लंबे समय तक रहने पर साँस की बीमारी; पहले से बीमार लोगों के लिए गंभीर।",
  "Avoid outdoor physical activity.": "बाहर शारीरिक गतिविधि से बचें।",
  "Keep windows closed; use an air purifier if available.": "खिड़कियाँ बंद रखें; एयर प्यूरीफ़ायर हो तो चलाएँ।",
  "Wear an N95 mask if you must go out.": "बाहर जाना ही हो तो N95 मास्क पहनें।",
  "Affects healthy people and seriously affects those with existing disease.": "स्वस्थ लोगों पर भी असर, और बीमारों पर गंभीर असर।",
  "Stay indoors; avoid all outdoor exertion.": "घर के अंदर रहें; बाहर की सारी मेहनत से बचें।",
  "Keep windows closed and run an air purifier.": "खिड़कियाँ बंद रखें और एयर प्यूरीफ़ायर चलाएँ।",
  "Schools and outdoor events should consider closure.": "स्कूल और बाहरी आयोजन बंद करने पर विचार करें।",
  "Scenario controls": "परिदृश्य नियंत्रण",
  "Change the conditions and re-run the whole coupled system.": "स्थितियाँ बदलें और पूरा सिस्टम दोबारा चलाएँ।",
  "Stubble fire load": "पराली की आग की मात्रा",
  "Wind speed": "हवा की गति",
  "Mixing depth (PBL)": "मिश्रण ऊँचाई (PBL)",
  "Starting haze (PM2.5)": "शुरुआती धुंध (PM2.5)",
  "fires": "आग",
  "of forecast": "पूर्वानुमान का",
  "Run scenario": "परिदृश्य चलाएँ",
  "Running…": "चल रहा है…",

  // modules: GRAP
  "GRAP stage forecast": "ग्रैप (GRAP) चरण पूर्वानुमान",
  "Which stage of Delhi's Graded Response Action Plan the forecast AQI would trigger.": "पूर्वानुमानित AQI दिल्ली की ग्रेडेड रिस्पॉन्स एक्शन प्लान (GRAP) का कौन-सा चरण लागू करवाएगा।",
  "at the chosen hour": "चुने गए घंटे पर",
  "Stage": "चरण",
  "No GRAP stage is expected in the next 72 hours.": "अगले 72 घंटों में कोई GRAP चरण अपेक्षित नहीं।",
  "Highest expected in 72 h": "72 घंटे में सबसे ऊँचा अपेक्षित",
  "Typical actions at this stage (plus all earlier stages)": "इस चरण के सामान्य कदम (और पिछले सभी चरणों के भी)",
  "Indicative only: based on forecast Delhi-mean AQI. The real GRAP decision is made by CAQM; check thresholds and actions against the current order.": "केवल संकेतात्मक: पूर्वानुमानित दिल्ली-औसत AQI पर आधारित। असली GRAP निर्णय CAQM लेता है; सीमाएँ और कदम वर्तमान आदेश से मिलाएँ।",
  "Below Stage I": "चरण I से नीचे",
  "No GRAP stage is triggered at this AQI.": "इस AQI पर कोई GRAP चरण लागू नहीं होता।",
  "Stage I · Poor (AQI 201–300)": "चरण I · खराब (AQI 201–300)",
  "Stage II · Very Poor (AQI 301–400)": "चरण II · बहुत खराब (AQI 301–400)",
  "Stage III · Severe (AQI 401–450)": "चरण III · गंभीर (AQI 401–450)",
  "Stage IV · Severe+ (AQI above 450)": "चरण IV · गंभीर+ (AQI 450 से ऊपर)",
  "Strict dust control: water sprinkling and mechanised road sweeping": "धूल पर सख़्त नियंत्रण: पानी का छिड़काव और मशीन से सड़क की सफ़ाई",
  "No open burning of waste or biomass": "कचरे या बायोमास को खुले में जलाना बंद",
  "Check vehicle pollution certificates and industrial emission norms": "वाहनों के प्रदूषण प्रमाणपत्र और उद्योगों के उत्सर्जन मानकों की जाँच",
  "Encourage public transport": "सार्वजनिक परिवहन को बढ़ावा",
  "Restrict diesel generator sets except essential services": "ज़रूरी सेवाओं को छोड़कर डीज़ल जनरेटर पर रोक",
  "Higher parking fees to discourage private cars": "निजी कारों को हतोत्साहित करने के लिए पार्किंग शुल्क बढ़ाना",
  "Run more metro and bus trips": "मेट्रो और बस के फेरे बढ़ाना",
  "No coal or firewood in eateries": "भोजनालयों में कोयला या लकड़ी का इस्तेमाल बंद",
  "Pause non-essential construction and demolition": "गैर-ज़रूरी निर्माण और तोड़फोड़ रोकना",
  "Restrict older petrol and diesel vehicles": "पुराने पेट्रोल और डीज़ल वाहनों पर रोक",
  "Limit entry of polluting trucks": "प्रदूषण फैलाने वाले ट्रकों का प्रवेश सीमित करना",
  "Consider hybrid classes for younger school children": "छोटे बच्चों के लिए हाइब्रिड कक्षाओं पर विचार",
  "Stop entry of non-essential trucks": "गैर-ज़रूरी ट्रकों का प्रवेश रोकना",
  "Pause public construction projects": "सार्वजनिक निर्माण परियोजनाएँ रोकना",
  "Consider odd-even rules for private cars": "निजी कारों पर ऑड-ईवन नियम पर विचार",
  "Consider school closures and work from home for offices": "स्कूल बंद करने और दफ़्तरों में घर से काम पर विचार",

  // modules: ozone
  "Ozone and NOx": "ओज़ोन और NOx",
  "Ozone is made by sunlight, so it peaks in the afternoon. NO₂ builds up at night when a shallow mixing layer traps traffic emissions.": "ओज़ोन धूप से बनती है, इसलिए दोपहर में चरम पर होती है। रात में उथली परत वाहनों का धुआँ फँसा लेती है और NO₂ बढ़ता है।",
  "Ozone (µg/m³)": "ओज़ोन (µg/m³)",
  "NO₂ (µg/m³)": "NO₂ (µg/m³)",
  "Ozone peak (first day)": "ओज़ोन का शिखर (पहला दिन)",
  "around": "लगभग",
  "Hours above the 8-h ozone standard": "8-घंटे के ओज़ोन मानक से ऊपर के घंटे",
  "limit": "सीमा",
  "NO₂ night vs daytime": "NO₂ रात बनाम दिन",
  "higher at night": "रात में ज़्यादा",
  "NO₂ tracks the trapping lid": "NO₂ फँसाने वाले ढक्कन के साथ चलता है",
  "vs 1 / PBL height": "बनाम 1 / PBL ऊँचाई",

  // modules: drivers
  "Why this forecast?": "यह पूर्वानुमान क्यों?",
  "What pushes the model's PM2.5 forecast up or down at the chosen hour, compared with an average case.": "चुने गए घंटे पर क्या मॉडल के PM2.5 पूर्वानुमान को औसत स्थिति की तुलना में ऊपर या नीचे ले जाता है।",
  "Effect on PM2.5 (%)": "PM2.5 पर असर (%)",
  "Red raises": "लाल बढ़ाता है",
  "blue lowers": "नीला घटाता है",
  "versus an average case of about": "औसत स्थिति लगभग",
  "Explains the machine-learned step, before the feedback loop and the stubble plume.": "यह मशीन-लर्निंग वाले चरण को समझाता है, फीडबैक और पराली के धुएँ से पहले का।",
  "Air right now": "अभी की हवा",
  "Smoke arriving from upwind": "हवा के ऊपरी ओर से आता धुआँ",
  "Wind and ventilation": "हवा और बहाव",
  "Inversion (warm lid)": "इन्वर्जन (गर्म ढक्कन)",
  "Temperature and sunlight": "तापमान और धूप",
  "Humidity and rain": "नमी और बारिश",
  "Time of day and season": "दिन का समय और मौसम",
  "Place and lead time": "स्थान और पूर्वानुमान की अवधि",

  // modules: source region
  "Where did Delhi's air come from?": "दिल्ली की हवा कहाँ से आई?",
  "Wind run backwards for 72 hours from Delhi, for air arriving at the chosen hour.": "चुने गए घंटे पर पहुँचने वाली हवा के लिए, दिल्ली से 72 घंटे पीछे की ओर हवा का रास्ता।",
  "Air arriving around": "लगभग इस समय पहुँचने वाली हवा",
  "came mostly from the": "ज़्यादातर आई",
  "about": "लगभग",
  "away 24 hours earlier.": "दूर से, 24 घंटे पहले।",
  "Paths crossing the stubble belt": "पराली क्षेत्र से गुज़रे रास्ते",
  "Fire power passed near": "पास से गुज़री आग की शक्ति",
  "of the region's total": "क्षेत्र के कुल का",
  "Paths shown on the map": "रास्ते नक्शे पर दिख रहे हैं",
  "Show paths on the map": "रास्ते नक्शे पर दिखाएँ",
  "Ten paths per arrival time, spread around Delhi; fires counted within 30 km of any path. A transport pattern, not a source-apportionment study.": "हर पहुँचने के समय के लिए दस रास्ते, दिल्ली के आसपास फैले; किसी रास्ते के 30 किमी के भीतर की आग गिनी गई। यह परिवहन का पैटर्न है, स्रोत-विभाजन अध्ययन नहीं।",
  "north": "उत्तर",
  "north-east": "उत्तर-पूर्व",
  "east": "पूर्व",
  "south-east": "दक्षिण-पूर्व",
  "south": "दक्षिण",
  "south-west": "दक्षिण-पश्चिम",
  "west": "पश्चिम",
  "north-west": "उत्तर-पश्चिम",

  // sections
  "Built on open data": "खुले डेटा पर आधारित",
  "Weather and pollution, finally in one loop.": "मौसम और प्रदूषण, आख़िरकार एक ही चक्र में।",
  "Standard AQI models treat meteorology and chemistry separately. In Delhi they push on each other.": "सामान्य AQI मॉडल मौसम और रसायन को अलग मानते हैं। दिल्ली में वे एक-दूसरे को धक्का देते हैं।",
  "Dense PM2.5 dims sunlight, cools the surface and shrinks the boundary layer — which traps more PM2.5. AirCouple iterates that loop until it settles.": "घना PM2.5 धूप घटाता है, सतह को ठंडा करता है और सीमा परत को सिकोड़ता है, जिससे और PM2.5 फँसता है। AirCouple इस चक्र को स्थिर होने तक दोहराता है।",
  "Inversion tracking": "इन्वर्जन ट्रैकिंग",
  "Stubble plume dispersion": "पराली के धुएँ का फैलाव",
  "Satellite fire detections over Punjab and Haryana are advected by the forecast wind; a shallow mixed layer amplifies what arrives in Delhi.": "पंजाब और हरियाणा में उपग्रह से मिली आग की पहचान पूर्वानुमानित हवा के साथ बहती है; उथली परत दिल्ली पहुँचने वाले धुएँ को और बढ़ा देती है।",
  "Tested on a season it never saw.": "ऐसे मौसम पर परखा गया जो उसने कभी नहीं देखा।",
  "Everything in one dashboard.": "सब कुछ एक डैशबोर्ड में।",
  "Twelve modules, each answering a question a forecaster, planner or citizen would ask.": "बारह मॉड्यूल, हर एक उस सवाल का जवाब जो कोई पूर्वानुमानकर्ता, योजनाकार या नागरिक पूछेगा।",
  "Smoke dims sunlight, the surface cools, the mixing layer shrinks, PM2.5 rises. Iterated to a stable answer.": "धुआँ धूप घटाता है, सतह ठंडी होती है, परत सिकुड़ती है, PM2.5 बढ़ता है। स्थिर उत्तर तक दोहराया जाता है।",
  "Strength, PBL height, ventilation and a trapping factor, every hour.": "इन्वर्जन की ताकत, PBL ऊँचाई, हवा का बहाव और फँसाव गुणक, हर घंटे।",
  "Satellite fires carried to Delhi on the forecast wind; a shallow lid amplifies the spike.": "उपग्रह से मिली आग का धुआँ हवा के साथ दिल्ली पहुँचता है; उथला ढक्कन उछाल को बढ़ाता है।",
  "Source region": "स्रोत क्षेत्र",
  "Wind run backwards from Delhi shows where the air came from and how much fire it passed.": "दिल्ली से पीछे की ओर चलाई गई हवा दिखाती है कि हवा कहाँ से आई और कितनी आग के पास से गुज़री।",
  "Afternoon ozone peaks and night-time NO₂ build-up under the lid.": "दोपहर में ओज़ोन का शिखर और रात में ढक्कन के नीचे NO₂ का जमाव।",
  "Which Graded Response Action Plan stage the forecast AQI would trigger, with typical actions.": "पूर्वानुमानित AQI से GRAP का कौन-सा चरण लागू होगा, सामान्य कदमों सहित।",
  "Attribution and drivers": "कारण और प्रभावित करने वाले तत्व",
  "Background vs stubble vs feedback, and which conditions push the forecast up or down.": "पृष्ठभूमि बनाम पराली बनाम फीडबैक, और कौन-सी स्थितियाँ पूर्वानुमान को ऊपर-नीचे करती हैं।",
  "Uncertainty and validation": "अनिश्चितता और सत्यापन",
  "A likely range, a real-episode replay, error by place and category, and a live check against CAMS.": "संभावित दायरा, असली दौर की दोबारा जाँच, स्थान और श्रेणी के अनुसार त्रुटि, और CAMS से लाइव मिलान।",
  "Change fires, wind, mixing depth and starting haze, and re-run the whole system.": "आग, हवा, मिश्रण ऊँचाई और शुरुआती धुंध बदलें, और पूरा सिस्टम दोबारा चलाएँ।",
  "CPCB-style guidance with the best and worst hours to be outdoors.": "CPCB शैली की सलाह, बाहर रहने के सबसे अच्छे और सबसे खराब घंटों के साथ।",
  "Open data": "खुला डेटा",
  "Download the forecast as CSV or call the API; full docs included.": "पूर्वानुमान CSV में डाउनलोड करें या API से लें; पूरे दस्तावेज़ शामिल हैं।",
  "Hindi and English": "हिंदी और अंग्रेज़ी",
  "Switch language from the top bar; works on phones and installs like an app.": "ऊपर की पट्टी से भाषा बदलें; फ़ोन पर चलता है और ऐप की तरह इंस्टॉल हो जाता है।",
  "Is this a real WRF-Chem run?": "क्या यह असली WRF-Chem रन है?",
  "Where does the data come from?": "डेटा कहाँ से आता है?",
  "What is the stubble-season what-if?": "पराली-मौसम का 'क्या होगा' क्या है?",
  "What are the known limitations?": "ज्ञात सीमाएँ क्या हैं?",
  "Ministry of Earth Sciences / NCMRWF": "पृथ्वी विज्ञान मंत्रालय / NCMRWF",
  "Data": "डेटा",

  // replay and validation
  "Replay a real haze episode.": "असली धुंध-दौर को दोहराएँ।",
  "Five forecasts issued during the Oct–Nov 2025 stubble season by a model that had never seen that season, compared with what actually happened.": "अक्टूबर–नवंबर 2025 के पराली-मौसम में दिए गए पाँच पूर्वानुमान, उस मॉडल से जिसने वह मौसम कभी नहीं देखा था, और जो वास्तव में हुआ उससे तुलना।",
  "Backtest not generated yet": "बैकटेस्ट अभी तैयार नहीं हुआ",
  "Delhi-mean PM2.5 · forecast issued": "दिल्ली-औसत PM2.5 · पूर्वानुमान जारी",
  "What actually happened (CAMS analysis)": "जो वास्तव में हुआ (CAMS विश्लेषण)",
  "AirCouple 72 h forecast": "AirCouple का 72 घंटे का पूर्वानुमान",
  "Persistence (no forecast)": "'जैसा है वैसा रहेगा' (कोई पूर्वानुमान नहीं)",
  "vs persistence": "बनाम 'जैसा है वैसा'",
  "Peak": "शिखर",
  "forecast vs": "पूर्वानुमान बनाम",
  "actual": "वास्तविक",
  "Bias": "झुकाव",
  "AQI category right": "AQI श्रेणी सही",
  "of hours": "घंटों में",
  "Range covered the truth": "दायरे ने सच को कवर किया",
  "All 5 episodes": "सभी 5 दौर",
  "better": "बेहतर",
  "Honest note: in these replays the two-way feedback term changes average MAE from": "ईमानदार टिप्पणी: इन दोहरावों में दोतरफ़ा फीडबैक औसत त्रुटि (MAE) को बदलता है",
  "uncoupled": "बिना फीडबैक",
  "to": "से",
  "it is not a measurable skill gain here; its value is physical consistency and response to what-if conditions. The Oct 28 forecast under-predicts a rising episode.": "यहाँ यह मापने योग्य सटीकता-वृद्धि नहीं है; इसका मूल्य भौतिक संगति और 'क्या होगा' स्थितियों पर प्रतिक्रिया है। 28 अक्टूबर का पूर्वानुमान बढ़ते दौर को कम आँकता है।",
  "Check our work.": "हमारी जाँच देखें।",
  "Error by lead time, by place, by AQI category, and a live check that grows the longer the server runs.": "समय-सीमा, स्थान और AQI श्रेणी के अनुसार त्रुटि, और एक लाइव जाँच जो सर्वर जितना चले उतनी बढ़ती है।",
  "Validation not generated yet": "सत्यापन अभी तैयार नहीं हुआ",
  "By lead time": "पूर्वानुमान की अवधि के अनुसार",
  "By station": "स्थान के अनुसार",
  "AQI categories": "AQI श्रेणियाँ",
  "Live check": "लाइव जाँच",
  "AirCouple": "AirCouple",
  "No change (persistence)": "कोई बदलाव नहीं (जैसा है वैसा)",
  "Mean absolute error of PM2.5 (µg/m³) at each forecast lead time, on the held-out stubble season. Lower is better.": "हर पूर्वानुमान-अवधि पर PM2.5 की औसत निरपेक्ष त्रुटि (µg/m³), उस पराली-मौसम पर जो प्रशिक्षण में नहीं था। कम बेहतर है।",
  "PM2.5 error per place (µg/m³). Stations in the same area behave alike because they share the same source data.": "हर स्थान पर PM2.5 त्रुटि (µg/m³)। एक ही इलाके के स्थान एक जैसे व्यवहार करते हैं क्योंकि उनका स्रोत डेटा एक ही है।",
  "Exactly right": "बिल्कुल सही",
  "Within one category": "एक श्रेणी के भीतर",
  "Actual ↓ / Forecast →": "वास्तविक ↓ / पूर्वानुमान →",
  "Each row is what actually happened; the percentages show how often the forecast put it in each category.": "हर पंक्ति वह है जो वास्तव में हुआ; प्रतिशत दिखाते हैं कि पूर्वानुमान ने उसे कितनी बार हर श्रेणी में रखा।",
  "Could not load the live check.": "लाइव जाँच लोड नहीं हो सकी।",
  "Lead": "अवधि",
  "Hours scored": "आँके गए घंटे",
  "No change": "कोई बदलाव नहीं",
  "Range covered": "दायरे ने कवर किया",
  "live forecasts scored against what CAMS later reported for the same Delhi stations (error in µg/m³; lower is better).": "लाइव पूर्वानुमान, जिन्हें बाद में CAMS द्वारा उन्हीं दिल्ली स्थानों के लिए बताए गए मानों से आँका गया (त्रुटि µg/m³ में; कम बेहतर है)।",
  "No data yet.": "अभी कोई डेटा नहीं।",
  "forecasts logged": "पूर्वानुमान दर्ज",
  "Every live forecast is saved. Once its hours have passed it is scored against what CAMS reported afterwards, next to the CAMS forecast issued at the same moment: a genuine out-of-sample test.": "हर लाइव पूर्वानुमान सहेजा जाता है। उसके घंटे बीत जाने पर उसे बाद में CAMS द्वारा बताए गए मानों से आँका जाता है, उसी क्षण के CAMS पूर्वानुमान के साथ: एक सच्ची नमूने-से-बाहर परीक्षा।",
  // how it works: inversion card and FAQ answers
  "T(925 hPa) − T(surface), boundary-layer height and the ventilation coefficient show, hour by hour, when the atmosphere puts a lid on Delhi.":
    "T(925 hPa) − T(सतह), सीमा परत की ऊँचाई और हवा के बहाव का गुणांक घंटे-दर-घंटे दिखाते हैं कि वायुमंडल दिल्ली पर कब ढक्कन लगा देता है।",
  "No. WRF-Chem needs an HPC cluster and emission inventories. AirCouple is a reduced-order coupled emulation: a machine-learned chemistry step is iterated with a parameterised aerosol–radiation–boundary-layer feedback. It runs on a laptop in about 30 seconds, and it is built to accept WRF-Chem fields (T2m, T925, PBL height, wind, radiation, AOD) as a drop-in.":
    "नहीं। WRF-Chem के लिए HPC क्लस्टर और उत्सर्जन सूचियाँ चाहिए। AirCouple एक सरलीकृत जुड़ा हुआ अनुकरण है: मशीन-लर्निंग से सीखा रसायन-चरण, मापदंडों पर आधारित प्रदूषण–विकिरण–सीमा परत फीडबैक के साथ दोहराया जाता है। यह लैपटॉप पर लगभग 30 सेकंड में चलता है, और WRF-Chem के क्षेत्र (T2m, T925, PBL ऊँचाई, हवा, विकिरण, AOD) सीधे लेने के लिए बना है।",
  "Meteorology and CAMS composition (PM2.5, PM10, NO₂, O₃, AOD) via Open-Meteo; active fires from NASA FIRMS VIIRS; basemap from OpenStreetMap. No API keys are needed.":
    "मौसम और CAMS की संरचना (PM2.5, PM10, NO₂, O₃, AOD) Open-Meteo के ज़रिए; सक्रिय आग NASA FIRMS VIIRS से; नक्शा OpenStreetMap से। किसी API कुंजी की ज़रूरत नहीं।",
  "Real fires are rare outside October–November, so the what-if starts from a typical early-November haze, adds a synthetic burning day over Punjab and Haryana and applies stagnant winter conditions to today's forecast. It is clearly badged as a scenario.":
    "अक्टूबर–नवंबर के बाहर असली आग कम होती है, इसलिए 'क्या होगा' मोड नवंबर की शुरुआत जैसी धुंध से शुरू होता है, पंजाब और हरियाणा में एक कृत्रिम जलाने का दिन जोड़ता है और आज के पूर्वानुमान पर ठहरी हुई सर्दी की स्थितियाँ लगाता है। इसे साफ़ तौर पर परिदृश्य के रूप में चिह्नित किया गया है।",
  "Ground truth is CAMS analysis, not CPCB station readings. Archived meteorology is short-lead NWP, so long-lead skill in the hold-out is slightly optimistic. Feedback strengths are tunable constants within literature ranges, not fitted values. PM10 skill is weak because dust events are hard to forecast.":
    "तुलना का आधार CAMS विश्लेषण है, CPCB केंद्रों की रीडिंग नहीं। संग्रहित मौसम कम-अवधि का NWP है, इसलिए लंबी अवधि की सटीकता थोड़ी आशावादी है। फीडबैक की ताकतें साहित्य के दायरे के भीतर बदली जा सकने वाली स्थिरांक हैं, फ़िट किए गए मान नहीं। PM10 की सटीकता कमज़ोर है क्योंकि धूल की घटनाओं का पूर्वानुमान कठिन है।",
  // scenario labels sent by the backend
  "Live: real forecast + real NASA FIRMS fire detections": "लाइव: असली पूर्वानुमान + NASA FIRMS से असली आग की पहचान",
  "What-if: synthetic early-November stubble-burning day + stagnant winter inversion on today's forecast": "क्या होगा: नवंबर की शुरुआत जैसा पराली जलाने का कृत्रिम दिन + आज के पूर्वानुमान पर ठहरा हुआ सर्दी का इन्वर्जन",
  // briefing and ask
  "Today's briefing": "आज का सारांश",
  "A plain-language summary of this forecast. Numbers always come from the forecast; an AI model, if configured, only rephrases them.": "इस पूर्वानुमान का सरल भाषा में सारांश। संख्याएँ हमेशा पूर्वानुमान से आती हैं; AI मॉडल, यदि जुड़ा हो, केवल उन्हें दोबारा शब्दों में लिखता है।",
  "Writing…": "लिखा जा रहा है…",
  "Could not load the briefing.": "सारांश लोड नहीं हो सका।",
  "AI-generated": "AI द्वारा लिखा",
  "Template summary": "टेम्पलेट सारांश",
  "Ask AirCouple": "AirCouple से पूछें",
  "Ask about the forecast…": "पूर्वानुमान के बारे में पूछें…",
  "Ask": "पूछें",
  "Could not get an answer. Is the backend running?": "उत्तर नहीं मिल सका। क्या बैकएंड चल रहा है?",
  "Best time to go out?": "बाहर जाने का सबसे अच्छा समय?",
  "When is the worst?": "सबसे खराब समय कब है?",
  "Which GRAP stage?": "GRAP का कौन-सा चरण?",
  "Where is the air from?": "हवा कहाँ से आ रही है?",
}
